options:
  verbose: true
syncs: 
  sourcecode-unison-sync:
    src: '../Server'
    dest: '/mnt/www'
    sync_strategy: 'unison'
    sync_excludes: ['ignored_folder', '.ignored_dot_folder']
    sync_excludes_type: 'Name'
  mysqldata-unison-sync:
    src: '../Runtime/Mysql'
    dest: '/var/lib/mysql'
    sync_strategy: 'unison'
    sync_excludes: ['ignored_folder', '.ignored_dot_folder']
    sync_excludes_type: 'Name'
