version: '2'
services:
  mysql:
    build: mysql
    image: bravist/mysql-5.6:1.0
    volumes_from:
      - "mysql-data-docker"
    ports:
      - "3306:3306"
    environment:
      # 默认的root密码和需要新建的数据库、用户名、密码，若需要重新设置，需要删除volumes/mysql/下面的全部内容，然后重新build
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    restart: always
  php-fpm:
    build: php-fpm
    image: bravist/php-7.0-fpm-alpine:1.0
    links:
      - mysql
    volumes_from:
      - web-root-docker
    ports:
      - "9000:9000"
    restart: always
  nginx:
    build: nginx
    image: bravist/nginx:1.0
    links:
      - php-fpm
    volumes_from:
      - web-logs-docker
    ports:
      - "80:80"
    restart: always
  web-root-docker:
    image: busybox:latest
    volumes: 
      - "./Server:/mnt/www"
  web-logs-docker:
    image: busybox:latest
    volumes: 
      - "./Server/logs:/var/log"
  mysql-data-docker:
    image: busybox:latest
    volumes: 
      - "./Server/Mysql:/var/lib"

