version: '1.0'
services:
  mysql:
    build: mysql
    image: bravist/mysql
    volumes:
      - "./volumes/mysql:/apps/mysql"
    ports:
      - "3306:3306"
    environment:
      # 默认的root密码和需要新建的数据库、用户名、密码，若需要重新设置，需要删除volumes/mysql/下面的全部内容，然后重新build
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=developer
      - MYSQL_PASSWORD=developer
    restart: always
  php-fpm:
    build: php-fpm
    image: bravist/php7.0.11-fpm:1.0
    links:
      - mysql
    volumes-from:
      - web-root-docker
    ports:
      - "9000:9000"
    restart: always
  nginx:
    build: nginx
    image: bravist/nginx
    links:
      - phpfpm
    volumes_from:
      - phpfpm
    ports:
      - "80:80"
    restart: always

 web-root-docker:
    image: busybox:latest
    volumes: ./Server:/mnt/www 

