version: '2'
services:
  mysql:
    build: ./mysql
    volumes:
      - ../../data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=developer
      - MYSQL_PASSWORD=developer
      - MYSQL_ROOT_PASSWORD=root
    restart: always
  php-fpm:
    build: ./php-fpm
    image: bravist/php-7.0-fpm-alpine:1.0
    links:
      - mysql
      - redis
    volumes_from:
      - web_root_docker
    ports:
      - "9000:9000"
    restart: always
  nginx:
    build: nginx
    image: bravist/nginx:1.0
    links:
      - php-fpm
    volumes_from:
      - php-fpm
    volumes: 
      - "../../data/nginx/conf:/etc/nginx/conf.d"
      - /var/opt/gitlab:/var/opt/gitlab
      - /opt/gitlab:/opt/gitlab/
    # volumes: 
    #   - "../Runtime/logs/nginx:/var/log/nginx"
    ports:
      - "80:80"
    restart: always
  redis:
    build: ./redis
    image: bravist/redis:1.0
    ports:
      - "6379:6379"
    restart: always
  web_root_docker:
    image: tianon/true
    volumes: 
      - "../../www:/mnt/www"

