version: '2'
services:
  mariadb:
    build: ./mysql
    volumes:
      - /mnt/data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=developer
      - MYSQL_PASSWORD=developer
      - MYSQL_ROOT_PASSWORD=root
    restart: always
  php-fpm:
    build: ./php-fpm
    image: bravist/php-7.0-fpm-alpine:1.0
    links:
      - mariadb
    volumes_from:
      - web-root-docker
    ports:
      - "9000:9000"
    restart: always
  nginx:
    build: nginx
    image: bravist/nginx:1.0
    links:
      - php-fpm
    volumes_from:
      - php-fpm
    volumes: 
      - "../Runtime/Nginx:/etc/nginx/conf.d"
    # volumes: 
    #   - "../Runtime/logs/nginx:/var/log/nginx"
    ports:
      - "80:80"
    restart: always
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
  web-root-docker:
    image: busybox:latest
    volumes: 
      - "../Server:/mnt/www"

